services:
  postgres:
    restart: unless-stopped
    container_name: regtest_db
    image: postgres:17.4-alpine3.21@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    volumes:
      - postgres-data:/postgresql_data
      - ./data/pg/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_ADDITIONAL_DATABASES: regtest_cln1_alice,regtest_cln2_bob,regtest_cln3_charlie,regtest_cln4_dave,regtest_cln5_erin,regtest_lnd6_farid,regtest_eclair7_grace,regtest_cln0_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /postgresql_data
    ports:
      - "5889:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$$POSTGRES_USER", "--dbname=regtest_cln0_app" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bitcoind:
    container_name: regtest_bitcoind
    image: polarlightning/bitcoind:28.0@sha256:ff435d758c89f01823924e057d5d5e4206d350ae69dff5e0dc1bbc9c6a36d010
    restart: unless-stopped
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin/regtest
    command:
      -regtest=1
      -server=1
      -whitelist=0.0.0.0/0
      -txindex=1
      -debug=0
      -dns=0
      -dnsseed=0
      -networkactive=0
      -uacomment=tbkdevbitcoindregtest
      -printtoconsole=1
      -printpriority=1
      -logtimemicros=1
      -rpcauth=regtest:169f6ba28badca1d912ac0defebc8ceb$$2550c68dfde8ca3b4892415fa8779b6ea656a44e7af1642332afa06c1979e014
      -rpcauth=app:f821d634f8b4c2fa2c63fb88a184960e$$225d98d20183093c377a6090c86b9a740380067d092a203831d5ce3ba168cc6c
      -rpcauth=alice:5e191aea02d8e4ddc6ae20cd24f46032$$f9379455baec014bfc4010602b40609586ce2a6f09ede080f70cac9ef920b8da
      -rpcauth=bob:15c79f76cfcf280680e24e708e743d41$$b529fc69466a868790ddbc17f7ecc76d894b60a3f7f8e58a8832932445a73cb9
      -rpcauth=charlie:c32657f44f0302f9f0facd25f730a151$$c90dbe5778cd65b23e4f5d931452fd4cfa4dc9bf695bb530de6d1533ec2ca8bb
      -rpcauth=dave:94d43df76ac813b13c958f99fb0e44c4$$3dde024ded4adc112021ed97e4741c3710a52a8526076188c14b2358b594be05
      -rpcauth=erin:39558bb938c4932e9ab179d75552495e$$c2f8a80cf4496d340bf5777ce45183e6c05dd9470bf17e90ba9a3dcbfee223e2
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -zmqpubhashblock=tcp://0.0.0.0:28334
      -zmqpubhashtx=tcp://0.0.0.0:28335
      -fallbackfee=0.00000253
    expose:
      - "18443"
      - "28332"
      - "28333"
      - "28334"
      - "28335"
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "28335:28335"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "-chain=regtest", "-getinfo" ]
      interval: 10s
      retries: 5

  cln0_app:
    container_name: regtest_cln0_app
    image: polarlightning/clightning:24.11.1@sha256:36bdb7d1826b23264863905a85ae93e24548a4db6979420a1cac69e905f4a316
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cln1_alice:
        condition: service_healthy
      cln2_bob:
        condition: service_healthy
      cln3_charlie:
        condition: service_healthy
      cln4_dave:
        condition: service_healthy
      cln5_erin:
        condition: service_healthy
      lnd6_farid:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln0_app'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln0_app:regtest_cln0_app@regtest_db:5432/regtest_cln0_app'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=app'
      - '--bitcoin-rpcpassword=app'
      - '--grpc-host=0.0.0.0'
      - '--grpc-port=19935'
      - '--clnrest-host=0.0.0.0'
      - '--clnrest-port=3010'
      - '--clnrest-swagger-root=/swagger-ui'
      - '--network=regtest'
      - '--log-level=debug'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--log-file=-' # means to log to stdout also!
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln0_app/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln0_app/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln0_app/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln0_app/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln0_app/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln0_app/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln0_app/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19935:19846"
      - "13010:3010"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  cln1_alice:
    container_name: regtest_cln1_alice
    image: polarlightning/clightning:24.11.1@sha256:36bdb7d1826b23264863905a85ae93e24548a4db6979420a1cac69e905f4a316
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cln2_bob:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln1_alice'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln1_alice:regtest_cln1_alice@regtest_db:5432/regtest_cln1_alice'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=alice'
      - '--bitcoin-rpcpassword=alice'
      - '--grpc-host=0.0.0.0'
      - '--grpc-port=19935'
      - '--clnrest-host=0.0.0.0'
      - '--clnrest-port=3010'
      - '--clnrest-swagger-root=/swagger-ui'
      - '--network=regtest'
      - '--log-level=info'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--log-file=-' # means to log to stdout also!
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln1_alice/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln_common/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln_common/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln_common/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln_common/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln_common/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln_common/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19936:19846"
      - "14010:3010"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 5s
      retries: 10

  #cln1_alice_cdk_mint: #this is not working, use cdk with lnd and nutshell with cln if possible
  #  container_name: regtest_cln1_alice_cdk_mint
  #  image: thesimplekid/cdk-mintd:v0.7.4@sha256:9da05978f0e18a11ff08a2f6494d87bc2efdc1d70f733278f0c5dd4f74db1579
  #  restart: unless-stopped
  #  depends_on:
  #    cln1_alice:
  #      condition: service_healthy
  #  environment:
  #    - CDK_MINTD_URL=https://example.com
  #    - CDK_MINTD_LN_BACKEND=fakewallet
  #    - CDK_MINTD_LISTEN_HOST=0.0.0.0
  #    - CDK_MINTD_LISTEN_PORT=8085
  #    - CDK_MINTD_MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
  #    - CDK_MINTD_DATABASE=redb
  #    - CDK_MINTD_CACHE_BACKEND=memory
  #  command: ["cdk-mintd"]
  #  ports:
  #    - "18085:8085"

  cln1_alice_nutshell_mint:
    container_name: regtest_cln1_alice_nutshell_mint
    image: cashubtc/nutshell:0.20.0@sha256:fae7b126ecc2ca797f3f572e5e86b3623bda26fdee0f97489ea9e3d09089950b
    restart: unless-stopped
    depends_on:
      cln1_alice:
        condition: service_healthy
    links:
      - "cln1_alice:cln" # ca.pem is valid for DNS "cln" and "localhost"
    environment:
      # https://github.com/cashubtc/nutshell/blob/main/.env.example
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      # key from persona "alice#0" (e.g. persona --name alice --account 0)
      - MINT_PRIVATE_KEY=7eaab2f5e9359badb538722e23e6e65bb0c8265a707d317ec4b132ccd23aeb72
      - TOR=FALSE
      - DEBUG=TRUE
      - MINT_INFO_NAME=Alice CLN1 Nutshell Mint
      #- MINT_DATABASE=postgres://cashu:cashu@localhost:5432/cashu
      - MINT_BACKEND_BOLT11_SAT=CLNRestWallet
      - MINT_CLNREST_URL=https://cln:3010
      - MINT_CLNREST_CERT=/ca.pem
      - MINT_CLNREST_RUNE=/dummy.rune
    command: ["poetry", "run", "mint"]
    volumes:
      - ./data/cln_common/regtest/ca.pem:/ca.pem
      - ./data/cln1_alice/regtest/dummy.rune:/dummy.rune
    ports:
      - "13338:3338"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:3338/v1/info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  lnd6_farid_nutshell_mint:
    container_name: regtest_lnd6_farid_nutshell_mint
    image: cashubtc/nutshell:0.20.0@sha256:fae7b126ecc2ca797f3f572e5e86b3623bda26fdee0f97489ea9e3d09089950b
    restart: unless-stopped
    depends_on:
      lnd6_farid:
        condition: service_healthy
    environment:
      # https://github.com/cashubtc/nutshell/blob/main/.env.example
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      # key from persona "farid#0" (e.g. persona --name farid --account 0)
      - MINT_PRIVATE_KEY=86dba776879191422e05665faae11768a0c0695a201964791db0f4a9134e5b17
      - TOR=FALSE
      - DEBUG=TRUE
      - MINT_INFO_NAME=Farid LND6 Nutshell Mint
      #- MINT_DATABASE=postgres://cashu:cashu@localhost:5432/cashu
      - MINT_BACKEND_BOLT11_SAT=LndRestWallet
      - MINT_LND_REST_ENDPOINT=https://regtest_lnd6_farid:8080
      - MINT_LND_REST_CERT=/tls.cert
      - MINT_LND_REST_MACAROON=/admin-dummy.macaroon # use dummy file; we run lnd with `--no-macaroons` at the moment
      - MINT_LND_REST_CERT_VERIFY=False # otherwise fails with: `certificate verify failed: Hostname mismatch, certificate is not valid for 'regtest_lnd6_farid'.`
    command: ["poetry", "run", "mint"]
    volumes:
      - ./data/lnd_common/tls.cert:/tls.cert
      - ./data/lnd_common/admin-dummy.macaroon:/admin-dummy.macaroon
    ports:
      - "14338:3338"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:3338/v1/info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  lnd6_farid_nutshell_wallet:
    container_name: regtest_lnd6_farid_nutshell_wallet
    image: cashubtc/nutshell:0.20.0@sha256:fae7b126ecc2ca797f3f572e5e86b3623bda26fdee0f97489ea9e3d09089950b
    restart: unless-stopped
    depends_on:
      lnd6_farid_nutshell_mint:
        condition: service_healthy
    environment:
      - MINT_URL=http://regtest_lnd6_farid_nutshell_mint:3338
      - API_HOST=0.0.0.0
      - API_PORT=4448
      - TOR=FALSE
      - DEBUG=TRUE
    command: ["poetry", "run", "cashu", "-d"]
    volumes:
      - ./data/lnd_common/tls.cert:/tls.cert
    ports:
      - "14448:4448"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:4448/info || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  cln2_bob:
    container_name: regtest_cln2_bob
    #image: polarlightning/clightning:24.08.1
    # An LND instance will connect to this node and does not like version >v23.11.2
    # Always fails with "peer ${pubkey} is not online" (last checked: 2024-10-10)
    image: polarlightning/clightning:23.11.2@sha256:102916c20bf1397b450ca517dbc0569824fb10e03d63c452328b4ff444817a51
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cln3_charlie:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln2_bob'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln2_bob:regtest_cln2_bob@regtest_db:5432/regtest_cln2_bob'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=bob'
      - '--bitcoin-rpcpassword=bob'
      - '--grpc-port=19935'
      - '--network=regtest'
      - '--log-level=info'
      - '--log-file=-'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
      #- '--disable-plugin=offers' # TODO: 'offers' plugin errors with v24.05 - disable temporarily (see https://github.com/ElementsProject/lightning/pull/7379)
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln2_bob/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln_common/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln_common/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln_common/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln_common/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln_common/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln_common/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19937:19846"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 5s
      retries: 10

  cln3_charlie:
    container_name: regtest_cln3_charlie
    image: polarlightning/clightning:25.02@sha256:dd0eeb748bce27eb10e25369239abdc00f087975b3c5cb938a024450cab5f948
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cln5_erin:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln3_charlie'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln3_charlie:regtest_cln3_charlie@regtest_db:5432/regtest_cln3_charlie'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=charlie'
      - '--bitcoin-rpcpassword=charlie'
      - '--grpc-host=0.0.0.0'
      - '--grpc-port=19935'
      - '--network=regtest'
      - '--log-level=info'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--log-file=-' # means to log to stdout also!
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln3_charlie/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln_common/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln_common/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln_common/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln_common/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln_common/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln_common/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19938:19846"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 5s
      retries: 10

  cln4_dave:
    container_name: regtest_cln4_dave
    image: polarlightning/clightning:24.08.1@sha256:d073beb246786c6769f4a17ea4048ee86be0f9fe959bd7928d46a33894fe01f5
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln4_dave'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln4_dave:regtest_cln4_dave@regtest_db:5432/regtest_cln4_dave'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=dave'
      - '--bitcoin-rpcpassword=dave'
      - '--grpc-port=19935'
      - '--network=regtest'
      - '--log-level=info'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--log-file=-' # means to log to stdout also!
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln4_dave/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln_common/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln_common/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln_common/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln_common/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln_common/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln_common/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19939:19846"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 5s
      retries: 10

  cln5_erin:
    container_name: regtest_cln5_erin
    image: polarlightning/clightning:24.08.1@sha256:d073beb246786c6769f4a17ea4048ee86be0f9fe959bd7928d46a33894fe01f5
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      LIGHTNINGD_POSTGRES_NO_VACUUM: 1
    command:
      - '--alias=cln5_erin'
      - '--addr=0.0.0.0:19846'
      - '--wallet=postgres://regtest_cln5_erin:regtest_cln5_erin@regtest_db:5432/regtest_cln5_erin'
      - '--bitcoin-rpcconnect=regtest_bitcoind'
      - '--bitcoin-rpcport=18443'
      - '--bitcoin-rpcuser=erin'
      - '--bitcoin-rpcpassword=erin'
      - '--grpc-port=19935'
      - '--network=regtest'
      - '--log-level=info'
      - '--log-file=/home/clightning/.lightning/regtest/debug.log' # write log file for inspection
      - '--log-file=-' # means to log to stdout also!
      - '--funding-confirms=1'
      - '--database-upgrade=true' # required if a non-release version wants to (irrevocably!) upgrade the db
      - '--allow-deprecated-apis=false'
      - '--disable-dns'
      # see all dev options: https://github.com/ElementsProject/lightning/blob/v24.08.1/lightningd/options.c#L812
      - '--dev-fast-gossip'
      - '--dev-fast-reconnect'
      - '--dev-bitcoind-poll=1'
      - '--dev-allow-localhost' # Announce and allow announcements for localhost address
      - '--developer'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/cln5_erin/regtest/hsm_secret:/home/clightning/.lightning/regtest/hsm_secret:ro
      - ./data/cln_common/regtest/ca.pem:/home/clightning/.lightning/regtest/ca.pem
      - ./data/cln_common/regtest/ca-key.pem:/home/clightning/.lightning/regtest/ca-key.pem
      - ./data/cln_common/regtest/client.pem:/home/clightning/.lightning/regtest/client.pem
      - ./data/cln_common/regtest/client-key.pem:/home/clightning/.lightning/regtest/client-key.pem
      - ./data/cln_common/regtest/server.pem:/home/clightning/.lightning/regtest/server.pem
      - ./data/cln_common/regtest/server-key.pem:/home/clightning/.lightning/regtest/server-key.pem
    ports:
      - "19940:19846"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lightning-cli", "--network=regtest", "getinfo" ]
      interval: 5s
      retries: 10

  lnd6_farid:
    container_name: regtest_lnd6_farid
    image: polarlightning/lnd:0.18.5-beta@sha256:9afcfd14b2eef3461cf89dbe77e4ec61f55df09cce23d16006fabf8f9eb69c55
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      cln3_charlie:
        condition: service_healthy
      eclair7_grace:
        condition: service_healthy
    command:
      # see all options: https://docs.lightning.engineering/lightning-network-tools/lnd/lnd.conf
      - '--alias=lnd6_farid'
      - '--bitcoin.regtest'
      - '--bitcoin.node=bitcoind'
      - '--bitcoin.defaultchanconfs=1'
      - '--bitcoind.rpchost=regtest_bitcoind:18443'
      - '--bitcoind.zmqpubrawblock=tcp://regtest_bitcoind:28332'
      - '--bitcoind.zmqpubrawtx=tcp://regtest_bitcoind:28333'
      - '--bitcoind.rpcuser=regtest'
      - '--bitcoind.rpcpass=regtest'
      - '--db.backend=postgres'
      - '--db.postgres.dsn=postgresql://regtest_lnd6_farid:regtest_lnd6_farid@regtest_db:5432/regtest_lnd6_farid'
      - '--db.postgres.timeout=0'
      - '--listen=0.0.0.0:9735'
      - '--externalip=regtest_lnd6_farid:9735'
      - '--restlisten=regtest_lnd6_farid:8080'
      - '--rpclisten=regtest_lnd6_farid:10009'
      - '--rpclisten=localhost:10009' # needed for healthcheck
      - '--tlscertduration=876000h'
      #- '--debuglevel=info'
      - '--debuglevel=debug'
      - '--maxpendingchannels=21'
      - '--trickledelay=50'
      - '--accept-keysend'
      - '--accept-amp'
      - '--noseedbackup'
      # Skip setting up macaroons for now, as it does not work properly and ends up with exception
      # `io.grpc.StatusRuntimeException: UNKNOWN: verification failed: signature mismatch after caveat verification`
      - '--no-macaroons'
    volumes:
      # mount all certs/keys individually (to avoid creating files on the host system by the container)
      - ./data/lnd_common/tls.cert:/home/lnd/.lnd/tls.cert
      - ./data/lnd_common/tls.key:/home/lnd/.lnd/tls.key
    ports:
      - "19741:9735"
      - "19841:8080"
      - "19941:10009"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "lncli", "--network=regtest", "--no-macaroons", "getinfo" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  eclair_wallet_init:
      container_name: regtest_eclair_wallet_init
      build:
        context: ./data/eclair_wallet_init
        dockerfile: Dockerfile
      restart: no
      environment:
        RPC_HOST: regtest_bitcoind
        RPC_PORT: 18443
        RPC_USER: regtest
        RPC_PASSWORD: regtest
      depends_on:
        bitcoind:
          condition: service_healthy

  eclair7_grace:
    container_name: regtest_eclair7_grace
    image: polarlightning/eclair:0.11.0@sha256:20e30612035d3d72be7da86e4e8b895dc04ab455a8359c209f73a639c17e27ff
    restart: unless-stopped
    depends_on:
      bitcoind:
        condition: service_healthy
      postgres:
        condition: service_healthy
      eclair_wallet_init:
        condition: service_started
      cln3_charlie:
        condition: service_healthy 
    command:
      - 'polar-eclair'
      # see https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf
      - '--node-alias=eclair7_grace'
      - '--datadir=/home/eclair/.eclair'
      - '--chain=regtest'
      - '--server.public-ips.0=regtest_eclair7_grace'
      - '--server.port=9735'
      - '--api.enabled=true'
      - '--api.binding-ip=0.0.0.0'
      - '--api.port=8080'
      - '--api.password=eclair'
      - '--bitcoind.host=regtest_bitcoind'
      - '--bitcoind.rpcport=18443'
      - '--bitcoind.rpcuser=regtest'
      - '--bitcoind.rpcpassword=regtest'
      - '--bitcoind.zmqblock=tcp://regtest_bitcoind:28334' # block hash, not raw block!
      - '--bitcoind.zmqtx=tcp://regtest_bitcoind:28333'
      - '--bitcoind.wallet=wallet_eclair_grace7'
      - '--db.driver=postgres'
      - '--db.postgres.database=regtest_eclair7_grace'
      - '--db.postgres.host=regtest_db'
      - '--db.postgres.port=5432'
      - '--db.postgres.username=regtest_eclair7_grace'
      - '--db.postgres.password=regtest_eclair7_grace'
      - '--on-chain-fees.feerate-tolerance.ratio-low=0.00001'
      - '--on-chain-fees.feerate-tolerance.ratio-high=10000.0'
      - '--channel.max-htlc-value-in-flight-percent=100'
      - '--channel.max-htlc-value-in-flight-msat=5000000000000' # 50 BTC in msats
      - '--features.keysend=optional'
      - '--printToConsole=true'
    volumes:
      - ./data/eclair7_grace/node_seed.dat:/home/eclair/.eclair/node_seed.dat
      - ./data/eclair7_grace/channel_seed.dat:/home/eclair/.eclair/channel_seed.dat
    ports:
      - "20080:8080"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "eclair-cli", "-p eclair", "getinfo" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
      start_interval: 3s

  rtl:
    container_name: regtest_rtl
    image: shahanafarooqui/rtl:v0.15.8@sha256:54131152cba02a968d83fcc89c07426bfb979372f743649ba1e2626426a34dc0
    restart: unless-stopped
    depends_on:
      cln0_app:
        condition: service_healthy
      cln1_alice:
        condition: service_healthy
      lnd6_farid:
        condition: service_healthy
      eclair7_grace:
        condition: service_healthy
    environment:
      - PORT=3000
    ports:
      - "13000:3000"
    volumes:
      - ./data/rtl/RTL-Config.json:/RTL/RTL-Config.json
      - ./data/lnd_common/admin-dummy.macaroon:/RTL/macaroons/admin.macaroon
      - ./data/cln0_app/regtest/dummy.rtl.rune:/cln0-dummy.rune
      - ./data/cln1_alice/regtest/dummy.rtl.rune:/cln1-dummy.rune

volumes:
  bitcoind-data:
  postgres-data:
